### ISSUE TITLE
Add Z-ordering support

### ISSUE THREAD

**Issue by vnen** [MrGreenTea/GodotTiledImporter#14]
As I want some layers to be above the player, I could use the Z order as a custom property of the layer that gets imported with the tilemap.

**Comment by MrGreenTea** [comment]
Sounds like a good idea. The question is, how does it work with the Tiled editor? Would you set it as a custom property of the layer?

**Comment by vnen** [comment]
Yes, it would be a custom property of the layer (something like `z-order`, `z-index`, or simply `z`). It seems straightforward to do, but I'm won't have free time to work on it in a while.
