### ISSUE TITLE
Tilesets not in subfolders of the tilemap can't be imported

### ISSUE THREAD

**Issue by vichug** [MrGreenTea/GodotTiledImporter#6]
(as seen on the forum)
The plugin will always consider the path saved in the Tiled map as relative to root. So if you have a subfolder in which there is both the map and tilesets, the plugin won't find the tilesets because in the tiled map, there is just written the name of the tileset because it's in the same folder.. so the plugin will look for the tileset, relatively to the root... not sure i make a lot of sense so i'll try with an example :

you have the root : `res://`
a folder with a tiled map and tileset : `res://folder_for_tiled_files`
inside this folder you have the .json map and whatever (png ?) tileset :
`res://folder_for_tiled_files/tiled_tileset.png`
`res://folder_for_tiled_files/tiled_map.json`

The path to the tileset, inside the tiled_map.json, is written relatively to tiled_map.json, so there is no path ; just the name of the file :

```
    "tilesets":[ [...]
               { [...]
                 "image":"tiled_tileset.png",
                 [...]}],
```

Now if you try to import the map into Godot, the plugin will say :
`couldn't find the tileset: res://tiled_tileset.png`
It should have looked at : `res://folder_for_tiled_files/tiled_tileset.png`
So, there you go...
There is one case i just tested where you can have an organisaton more practical (imho) than just all the files at the root : you must have the .json at the root, and you can have the tileset in a subfolder. That way, the path to the tilesets that is written inside the .json map is the exact path to the tilesets relatively to the godot root.

**Comment by MrGreenTea** [comment]
The problem is, that godot needs a full path, like "res://path/to/tileset.png" and has no easy way of converting local paths that go up in folders with "../" to these paths. It shouldn't be that hard to write such a function myself, but it's not a high priority for me.

**Comment by vichug** [comment]
oh so the unix style ../ won't do the trick ?

**Comment by vichug** [comment]
but still, having both the map and the tilesets in the same folder should be straightforward, since the folder path to the map is the same as the folder path to the tilesets ?

**Comment by MrGreenTea** [comment]
No,  I don't think so. Having the tilemap and tileset in the same folder works fine, as long as the tileset images are in the same folder or in a subfolder of the tilemap. For example res://path/tilemap works, if the tileset is in res://path/tileset.png or res://path/deeper/path/tileset.png, but not if it's in res://other/path/tileset.png

**Comment by vichug** [comment]
hah, actually i was meaning that :
`res://path/tilemap works, if the tileset is in res://path/tileset.png or res://path/deeper/path/tileset.png`
which i tried before unsuccessfully, or so i thought
now i try, it works !.

**Comment by MrGreenTea** [comment]
Yeah I fixed it yesterday :)

**Comment by vichug** [comment]
Hah ! it's sometimes uneasy to be precise enough when discussing those things :)
