### ISSUE TITLE
Tiled spacing is not supported

### ISSUE THREAD

**Issue by tbruyelle** [MrGreenTea/GodotTiledImporter#7]
When a spacing value is specified in the tileset, the plugins doesn't work properly (the imported tilemap is messed up).

Exemple with this tileset 
the json : https://www.dropbox.com/s/407bfzr5rdlu2o0/test2.json?dl=0
the png : https://www.dropbox.com/s/d972k2c0dm3jqep/desert_palace_tiles_rescale.png?dl=0

**Comment by MrGreenTea** [comment]
I'll look into it, thanks for reporting.

**Comment by tbruyelle** [comment]
Thanks, please have a look to my PR above, I think I'm close to the goal.

Sorry for the poor python code, I'm not familiar with the language.

**Comment by MrGreenTea** [comment]
Sorry for letting you wait so long. I'll check it out when I find the time, but exams are keeping me busy right now.

**Comment by tbruyelle** [comment]
Ok don't worry I found another way.
